// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIV1StatusWorkflowNameParams creates a new DeleteAPIV1StatusWorkflowNameParams object
// with the default values initialized.
func NewDeleteAPIV1StatusWorkflowNameParams() *DeleteAPIV1StatusWorkflowNameParams {
	var ()
	return &DeleteAPIV1StatusWorkflowNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV1StatusWorkflowNameParamsWithTimeout creates a new DeleteAPIV1StatusWorkflowNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV1StatusWorkflowNameParamsWithTimeout(timeout time.Duration) *DeleteAPIV1StatusWorkflowNameParams {
	var ()
	return &DeleteAPIV1StatusWorkflowNameParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV1StatusWorkflowNameParamsWithContext creates a new DeleteAPIV1StatusWorkflowNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV1StatusWorkflowNameParamsWithContext(ctx context.Context) *DeleteAPIV1StatusWorkflowNameParams {
	var ()
	return &DeleteAPIV1StatusWorkflowNameParams{

		Context: ctx,
	}
}

// NewDeleteAPIV1StatusWorkflowNameParamsWithHTTPClient creates a new DeleteAPIV1StatusWorkflowNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV1StatusWorkflowNameParamsWithHTTPClient(client *http.Client) *DeleteAPIV1StatusWorkflowNameParams {
	var ()
	return &DeleteAPIV1StatusWorkflowNameParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV1StatusWorkflowNameParams contains all the parameters to send to the API endpoint
for the delete API v1 status workflow name operation typically these are written to a http.Request
*/
type DeleteAPIV1StatusWorkflowNameParams struct {

	/*Name
	  Name of the workflow status to be deleted.

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API v1 status workflow name params
func (o *DeleteAPIV1StatusWorkflowNameParams) WithTimeout(timeout time.Duration) *DeleteAPIV1StatusWorkflowNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v1 status workflow name params
func (o *DeleteAPIV1StatusWorkflowNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v1 status workflow name params
func (o *DeleteAPIV1StatusWorkflowNameParams) WithContext(ctx context.Context) *DeleteAPIV1StatusWorkflowNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v1 status workflow name params
func (o *DeleteAPIV1StatusWorkflowNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v1 status workflow name params
func (o *DeleteAPIV1StatusWorkflowNameParams) WithHTTPClient(client *http.Client) *DeleteAPIV1StatusWorkflowNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v1 status workflow name params
func (o *DeleteAPIV1StatusWorkflowNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete API v1 status workflow name params
func (o *DeleteAPIV1StatusWorkflowNameParams) WithName(name string) *DeleteAPIV1StatusWorkflowNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete API v1 status workflow name params
func (o *DeleteAPIV1StatusWorkflowNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV1StatusWorkflowNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
