// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetAPIV1StatusWorkflowNameReader is a Reader for the GetAPIV1StatusWorkflowName structure.
type GetAPIV1StatusWorkflowNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1StatusWorkflowNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1StatusWorkflowNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAPIV1StatusWorkflowNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV1StatusWorkflowNameOK creates a GetAPIV1StatusWorkflowNameOK with default headers values
func NewGetAPIV1StatusWorkflowNameOK() *GetAPIV1StatusWorkflowNameOK {
	return &GetAPIV1StatusWorkflowNameOK{}
}

/*GetAPIV1StatusWorkflowNameOK handles this case with default header values.

OK
*/
type GetAPIV1StatusWorkflowNameOK struct {
	Payload *models.ResponseRegistryItem
}

func (o *GetAPIV1StatusWorkflowNameOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/status/workflow/{name}][%d] getApiV1StatusWorkflowNameOK  %+v", 200, o.Payload)
}

func (o *GetAPIV1StatusWorkflowNameOK) GetPayload() *models.ResponseRegistryItem {
	return o.Payload
}

func (o *GetAPIV1StatusWorkflowNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseRegistryItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1StatusWorkflowNameInternalServerError creates a GetAPIV1StatusWorkflowNameInternalServerError with default headers values
func NewGetAPIV1StatusWorkflowNameInternalServerError() *GetAPIV1StatusWorkflowNameInternalServerError {
	return &GetAPIV1StatusWorkflowNameInternalServerError{}
}

/*GetAPIV1StatusWorkflowNameInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIV1StatusWorkflowNameInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *GetAPIV1StatusWorkflowNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/status/workflow/{name}][%d] getApiV1StatusWorkflowNameInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPIV1StatusWorkflowNameInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetAPIV1StatusWorkflowNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
