// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetAPIV1StatusWorkflowReader is a Reader for the GetAPIV1StatusWorkflow structure.
type GetAPIV1StatusWorkflowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1StatusWorkflowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1StatusWorkflowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAPIV1StatusWorkflowInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV1StatusWorkflowOK creates a GetAPIV1StatusWorkflowOK with default headers values
func NewGetAPIV1StatusWorkflowOK() *GetAPIV1StatusWorkflowOK {
	return &GetAPIV1StatusWorkflowOK{}
}

/*GetAPIV1StatusWorkflowOK handles this case with default header values.

OK
*/
type GetAPIV1StatusWorkflowOK struct {
	Payload *models.ResponseRegistryItem
}

func (o *GetAPIV1StatusWorkflowOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/status/workflow][%d] getApiV1StatusWorkflowOK  %+v", 200, o.Payload)
}

func (o *GetAPIV1StatusWorkflowOK) GetPayload() *models.ResponseRegistryItem {
	return o.Payload
}

func (o *GetAPIV1StatusWorkflowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseRegistryItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1StatusWorkflowInternalServerError creates a GetAPIV1StatusWorkflowInternalServerError with default headers values
func NewGetAPIV1StatusWorkflowInternalServerError() *GetAPIV1StatusWorkflowInternalServerError {
	return &GetAPIV1StatusWorkflowInternalServerError{}
}

/*GetAPIV1StatusWorkflowInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIV1StatusWorkflowInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *GetAPIV1StatusWorkflowInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/status/workflow][%d] getApiV1StatusWorkflowInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPIV1StatusWorkflowInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetAPIV1StatusWorkflowInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
