// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// PostAPIV1StatusWorkflowReader is a Reader for the PostAPIV1StatusWorkflow structure.
type PostAPIV1StatusWorkflowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1StatusWorkflowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1StatusWorkflowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1StatusWorkflowBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1StatusWorkflowInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV1StatusWorkflowOK creates a PostAPIV1StatusWorkflowOK with default headers values
func NewPostAPIV1StatusWorkflowOK() *PostAPIV1StatusWorkflowOK {
	return &PostAPIV1StatusWorkflowOK{}
}

/*PostAPIV1StatusWorkflowOK handles this case with default header values.

OK
*/
type PostAPIV1StatusWorkflowOK struct {
	Payload *models.ResponseHTTPMessage
}

func (o *PostAPIV1StatusWorkflowOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/status/workflow][%d] postApiV1StatusWorkflowOK  %+v", 200, o.Payload)
}

func (o *PostAPIV1StatusWorkflowOK) GetPayload() *models.ResponseHTTPMessage {
	return o.Payload
}

func (o *PostAPIV1StatusWorkflowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1StatusWorkflowBadRequest creates a PostAPIV1StatusWorkflowBadRequest with default headers values
func NewPostAPIV1StatusWorkflowBadRequest() *PostAPIV1StatusWorkflowBadRequest {
	return &PostAPIV1StatusWorkflowBadRequest{}
}

/*PostAPIV1StatusWorkflowBadRequest handles this case with default header values.

Bad Request
*/
type PostAPIV1StatusWorkflowBadRequest struct {
	Payload *models.ResponseHTTPError
}

func (o *PostAPIV1StatusWorkflowBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/status/workflow][%d] postApiV1StatusWorkflowBadRequest  %+v", 400, o.Payload)
}

func (o *PostAPIV1StatusWorkflowBadRequest) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *PostAPIV1StatusWorkflowBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1StatusWorkflowInternalServerError creates a PostAPIV1StatusWorkflowInternalServerError with default headers values
func NewPostAPIV1StatusWorkflowInternalServerError() *PostAPIV1StatusWorkflowInternalServerError {
	return &PostAPIV1StatusWorkflowInternalServerError{}
}

/*PostAPIV1StatusWorkflowInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostAPIV1StatusWorkflowInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *PostAPIV1StatusWorkflowInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/status/workflow][%d] postApiV1StatusWorkflowInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAPIV1StatusWorkflowInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *PostAPIV1StatusWorkflowInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
