// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIV1StatusWorkflowParams creates a new PostAPIV1StatusWorkflowParams object
// with the default values initialized.
func NewPostAPIV1StatusWorkflowParams() *PostAPIV1StatusWorkflowParams {
	var ()
	return &PostAPIV1StatusWorkflowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1StatusWorkflowParamsWithTimeout creates a new PostAPIV1StatusWorkflowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV1StatusWorkflowParamsWithTimeout(timeout time.Duration) *PostAPIV1StatusWorkflowParams {
	var ()
	return &PostAPIV1StatusWorkflowParams{

		timeout: timeout,
	}
}

// NewPostAPIV1StatusWorkflowParamsWithContext creates a new PostAPIV1StatusWorkflowParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV1StatusWorkflowParamsWithContext(ctx context.Context) *PostAPIV1StatusWorkflowParams {
	var ()
	return &PostAPIV1StatusWorkflowParams{

		Context: ctx,
	}
}

// NewPostAPIV1StatusWorkflowParamsWithHTTPClient creates a new PostAPIV1StatusWorkflowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV1StatusWorkflowParamsWithHTTPClient(client *http.Client) *PostAPIV1StatusWorkflowParams {
	var ()
	return &PostAPIV1StatusWorkflowParams{
		HTTPClient: client,
	}
}

/*PostAPIV1StatusWorkflowParams contains all the parameters to send to the API endpoint
for the post API v1 status workflow operation typically these are written to a http.Request
*/
type PostAPIV1StatusWorkflowParams struct {

	/*Workflow
	  WorkflowStatus manifest to be created.

	*/
	Workflow string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post API v1 status workflow params
func (o *PostAPIV1StatusWorkflowParams) WithTimeout(timeout time.Duration) *PostAPIV1StatusWorkflowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 status workflow params
func (o *PostAPIV1StatusWorkflowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 status workflow params
func (o *PostAPIV1StatusWorkflowParams) WithContext(ctx context.Context) *PostAPIV1StatusWorkflowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 status workflow params
func (o *PostAPIV1StatusWorkflowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 status workflow params
func (o *PostAPIV1StatusWorkflowParams) WithHTTPClient(client *http.Client) *PostAPIV1StatusWorkflowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 status workflow params
func (o *PostAPIV1StatusWorkflowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflow adds the workflow to the post API v1 status workflow params
func (o *PostAPIV1StatusWorkflowParams) WithWorkflow(workflow string) *PostAPIV1StatusWorkflowParams {
	o.SetWorkflow(workflow)
	return o
}

// SetWorkflow adds the workflow to the post API v1 status workflow params
func (o *PostAPIV1StatusWorkflowParams) SetWorkflow(workflow string) {
	o.Workflow = workflow
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1StatusWorkflowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param workflow
	frWorkflow := o.Workflow
	fWorkflow := frWorkflow
	if fWorkflow != "" {
		if err := r.SetFormParam("workflow", fWorkflow); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
