// Code generated by go-swagger; DO NOT EDIT.

package info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1InfoWorkflowNamePipelinePipelineParams creates a new GetAPIV1InfoWorkflowNamePipelinePipelineParams object
// with the default values initialized.
func NewGetAPIV1InfoWorkflowNamePipelinePipelineParams() *GetAPIV1InfoWorkflowNamePipelinePipelineParams {
	var ()
	return &GetAPIV1InfoWorkflowNamePipelinePipelineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1InfoWorkflowNamePipelinePipelineParamsWithTimeout creates a new GetAPIV1InfoWorkflowNamePipelinePipelineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1InfoWorkflowNamePipelinePipelineParamsWithTimeout(timeout time.Duration) *GetAPIV1InfoWorkflowNamePipelinePipelineParams {
	var ()
	return &GetAPIV1InfoWorkflowNamePipelinePipelineParams{

		timeout: timeout,
	}
}

// NewGetAPIV1InfoWorkflowNamePipelinePipelineParamsWithContext creates a new GetAPIV1InfoWorkflowNamePipelinePipelineParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1InfoWorkflowNamePipelinePipelineParamsWithContext(ctx context.Context) *GetAPIV1InfoWorkflowNamePipelinePipelineParams {
	var ()
	return &GetAPIV1InfoWorkflowNamePipelinePipelineParams{

		Context: ctx,
	}
}

// NewGetAPIV1InfoWorkflowNamePipelinePipelineParamsWithHTTPClient creates a new GetAPIV1InfoWorkflowNamePipelinePipelineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1InfoWorkflowNamePipelinePipelineParamsWithHTTPClient(client *http.Client) *GetAPIV1InfoWorkflowNamePipelinePipelineParams {
	var ()
	return &GetAPIV1InfoWorkflowNamePipelinePipelineParams{
		HTTPClient: client,
	}
}

/*GetAPIV1InfoWorkflowNamePipelinePipelineParams contains all the parameters to send to the API endpoint
for the get API v1 info workflow name pipeline pipeline operation typically these are written to a http.Request
*/
type GetAPIV1InfoWorkflowNamePipelinePipelineParams struct {

	/*Name
	  Name of the workflow to get information about.

	*/
	Name string
	/*Pipeline
	  Name of the pipeline to return the info about.

	*/
	Pipeline string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 info workflow name pipeline pipeline params
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) WithTimeout(timeout time.Duration) *GetAPIV1InfoWorkflowNamePipelinePipelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 info workflow name pipeline pipeline params
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 info workflow name pipeline pipeline params
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) WithContext(ctx context.Context) *GetAPIV1InfoWorkflowNamePipelinePipelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 info workflow name pipeline pipeline params
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 info workflow name pipeline pipeline params
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) WithHTTPClient(client *http.Client) *GetAPIV1InfoWorkflowNamePipelinePipelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 info workflow name pipeline pipeline params
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get API v1 info workflow name pipeline pipeline params
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) WithName(name string) *GetAPIV1InfoWorkflowNamePipelinePipelineParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get API v1 info workflow name pipeline pipeline params
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) SetName(name string) {
	o.Name = name
}

// WithPipeline adds the pipeline to the get API v1 info workflow name pipeline pipeline params
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) WithPipeline(pipeline string) *GetAPIV1InfoWorkflowNamePipelinePipelineParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the get API v1 info workflow name pipeline pipeline params
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
