// Code generated by go-swagger; DO NOT EDIT.

package info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetAPIV1InfoWorkflowNamePipelinePipelineReader is a Reader for the GetAPIV1InfoWorkflowNamePipelinePipeline structure.
type GetAPIV1InfoWorkflowNamePipelinePipelineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1InfoWorkflowNamePipelinePipelineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1InfoWorkflowNamePipelinePipelineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1InfoWorkflowNamePipelinePipelineBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV1InfoWorkflowNamePipelinePipelineOK creates a GetAPIV1InfoWorkflowNamePipelinePipelineOK with default headers values
func NewGetAPIV1InfoWorkflowNamePipelinePipelineOK() *GetAPIV1InfoWorkflowNamePipelinePipelineOK {
	return &GetAPIV1InfoWorkflowNamePipelinePipelineOK{}
}

/*GetAPIV1InfoWorkflowNamePipelinePipelineOK handles this case with default header values.

OK
*/
type GetAPIV1InfoWorkflowNamePipelinePipelineOK struct {
	Payload *models.ResponsePipelineInfo
}

func (o *GetAPIV1InfoWorkflowNamePipelinePipelineOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/info/workflow/{name}/pipeline/{pipeline}][%d] getApiV1InfoWorkflowNamePipelinePipelineOK  %+v", 200, o.Payload)
}

func (o *GetAPIV1InfoWorkflowNamePipelinePipelineOK) GetPayload() *models.ResponsePipelineInfo {
	return o.Payload
}

func (o *GetAPIV1InfoWorkflowNamePipelinePipelineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsePipelineInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1InfoWorkflowNamePipelinePipelineBadRequest creates a GetAPIV1InfoWorkflowNamePipelinePipelineBadRequest with default headers values
func NewGetAPIV1InfoWorkflowNamePipelinePipelineBadRequest() *GetAPIV1InfoWorkflowNamePipelinePipelineBadRequest {
	return &GetAPIV1InfoWorkflowNamePipelinePipelineBadRequest{}
}

/*GetAPIV1InfoWorkflowNamePipelinePipelineBadRequest handles this case with default header values.

Bad Request
*/
type GetAPIV1InfoWorkflowNamePipelinePipelineBadRequest struct {
	Payload *models.ResponseHTTPError
}

func (o *GetAPIV1InfoWorkflowNamePipelinePipelineBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/info/workflow/{name}/pipeline/{pipeline}][%d] getApiV1InfoWorkflowNamePipelinePipelineBadRequest  %+v", 400, o.Payload)
}

func (o *GetAPIV1InfoWorkflowNamePipelinePipelineBadRequest) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetAPIV1InfoWorkflowNamePipelinePipelineBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError creates a GetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError with default headers values
func NewGetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError() *GetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError {
	return &GetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError{}
}

/*GetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *GetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/info/workflow/{name}/pipeline/{pipeline}][%d] getApiV1InfoWorkflowNamePipelinePipelineInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetAPIV1InfoWorkflowNamePipelinePipelineInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
