// Code generated by go-swagger; DO NOT EDIT.

package info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetAPIV1InfoWorkflowNameReader is a Reader for the GetAPIV1InfoWorkflowName structure.
type GetAPIV1InfoWorkflowNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1InfoWorkflowNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1InfoWorkflowNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV1InfoWorkflowNameOK creates a GetAPIV1InfoWorkflowNameOK with default headers values
func NewGetAPIV1InfoWorkflowNameOK() *GetAPIV1InfoWorkflowNameOK {
	return &GetAPIV1InfoWorkflowNameOK{}
}

/*GetAPIV1InfoWorkflowNameOK handles this case with default header values.

OK
*/
type GetAPIV1InfoWorkflowNameOK struct {
	Payload models.ResponseWorkflowVerboseInfo
}

func (o *GetAPIV1InfoWorkflowNameOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/info/workflow/{name}][%d] getApiV1InfoWorkflowNameOK  %+v", 200, o.Payload)
}

func (o *GetAPIV1InfoWorkflowNameOK) GetPayload() models.ResponseWorkflowVerboseInfo {
	return o.Payload
}

func (o *GetAPIV1InfoWorkflowNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
