// Code generated by go-swagger; DO NOT EDIT.

package info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetAPIV1InfoWorkflowWorkflowPipelinePipelineReader is a Reader for the GetAPIV1InfoWorkflowWorkflowPipelinePipeline structure.
type GetAPIV1InfoWorkflowWorkflowPipelinePipelineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineOK creates a GetAPIV1InfoWorkflowWorkflowPipelinePipelineOK with default headers values
func NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineOK() *GetAPIV1InfoWorkflowWorkflowPipelinePipelineOK {
	return &GetAPIV1InfoWorkflowWorkflowPipelinePipelineOK{}
}

/*GetAPIV1InfoWorkflowWorkflowPipelinePipelineOK handles this case with default header values.

OK
*/
type GetAPIV1InfoWorkflowWorkflowPipelinePipelineOK struct {
	Payload *models.ResponsePipelineInfo
}

func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/info/workflow/{workflow}/pipeline/{pipeline}][%d] getApiV1InfoWorkflowWorkflowPipelinePipelineOK  %+v", 200, o.Payload)
}

func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineOK) GetPayload() *models.ResponsePipelineInfo {
	return o.Payload
}

func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsePipelineInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest creates a GetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest with default headers values
func NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest() *GetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest {
	return &GetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest{}
}

/*GetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest handles this case with default header values.

Bad Request
*/
type GetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest struct {
	Payload *models.ResponseHTTPError
}

func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/info/workflow/{workflow}/pipeline/{pipeline}][%d] getApiV1InfoWorkflowWorkflowPipelinePipelineBadRequest  %+v", 400, o.Payload)
}

func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError creates a GetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError with default headers values
func NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError() *GetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError {
	return &GetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError{}
}

/*GetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/info/workflow/{workflow}/pipeline/{pipeline}][%d] getApiV1InfoWorkflowWorkflowPipelinePipelineInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
