// Code generated by go-swagger; DO NOT EDIT.

package info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1InfoAgentNameParams creates a new GetAPIV1InfoAgentNameParams object
// with the default values initialized.
func NewGetAPIV1InfoAgentNameParams() *GetAPIV1InfoAgentNameParams {
	var ()
	return &GetAPIV1InfoAgentNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1InfoAgentNameParamsWithTimeout creates a new GetAPIV1InfoAgentNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1InfoAgentNameParamsWithTimeout(timeout time.Duration) *GetAPIV1InfoAgentNameParams {
	var ()
	return &GetAPIV1InfoAgentNameParams{

		timeout: timeout,
	}
}

// NewGetAPIV1InfoAgentNameParamsWithContext creates a new GetAPIV1InfoAgentNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1InfoAgentNameParamsWithContext(ctx context.Context) *GetAPIV1InfoAgentNameParams {
	var ()
	return &GetAPIV1InfoAgentNameParams{

		Context: ctx,
	}
}

// NewGetAPIV1InfoAgentNameParamsWithHTTPClient creates a new GetAPIV1InfoAgentNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1InfoAgentNameParamsWithHTTPClient(client *http.Client) *GetAPIV1InfoAgentNameParams {
	var ()
	return &GetAPIV1InfoAgentNameParams{
		HTTPClient: client,
	}
}

/*GetAPIV1InfoAgentNameParams contains all the parameters to send to the API endpoint
for the get API v1 info agent name operation typically these are written to a http.Request
*/
type GetAPIV1InfoAgentNameParams struct {

	/*Name
	  Name of the agent to get information about.

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 info agent name params
func (o *GetAPIV1InfoAgentNameParams) WithTimeout(timeout time.Duration) *GetAPIV1InfoAgentNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 info agent name params
func (o *GetAPIV1InfoAgentNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 info agent name params
func (o *GetAPIV1InfoAgentNameParams) WithContext(ctx context.Context) *GetAPIV1InfoAgentNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 info agent name params
func (o *GetAPIV1InfoAgentNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 info agent name params
func (o *GetAPIV1InfoAgentNameParams) WithHTTPClient(client *http.Client) *GetAPIV1InfoAgentNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 info agent name params
func (o *GetAPIV1InfoAgentNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get API v1 info agent name params
func (o *GetAPIV1InfoAgentNameParams) WithName(name string) *GetAPIV1InfoAgentNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get API v1 info agent name params
func (o *GetAPIV1InfoAgentNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1InfoAgentNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
