// Code generated by go-swagger; DO NOT EDIT.

package info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineParams creates a new GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams object
// with the default values initialized.
func NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineParams() *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams {
	var ()
	return &GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineParamsWithTimeout creates a new GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineParamsWithTimeout(timeout time.Duration) *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams {
	var ()
	return &GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams{

		timeout: timeout,
	}
}

// NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineParamsWithContext creates a new GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineParamsWithContext(ctx context.Context) *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams {
	var ()
	return &GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams{

		Context: ctx,
	}
}

// NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineParamsWithHTTPClient creates a new GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1InfoWorkflowWorkflowPipelinePipelineParamsWithHTTPClient(client *http.Client) *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams {
	var ()
	return &GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams{
		HTTPClient: client,
	}
}

/*GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams contains all the parameters to send to the API endpoint
for the get API v1 info workflow workflow pipeline pipeline operation typically these are written to a http.Request
*/
type GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams struct {

	/*Pipeline
	  Name of the pipeline to return the info about.

	*/
	Pipeline string
	/*Workflow
	  Name of the workflow to get information about.

	*/
	Workflow string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 info workflow workflow pipeline pipeline params
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) WithTimeout(timeout time.Duration) *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 info workflow workflow pipeline pipeline params
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 info workflow workflow pipeline pipeline params
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) WithContext(ctx context.Context) *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 info workflow workflow pipeline pipeline params
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 info workflow workflow pipeline pipeline params
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) WithHTTPClient(client *http.Client) *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 info workflow workflow pipeline pipeline params
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPipeline adds the pipeline to the get API v1 info workflow workflow pipeline pipeline params
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) WithPipeline(pipeline string) *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the get API v1 info workflow workflow pipeline pipeline params
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WithWorkflow adds the workflow to the get API v1 info workflow workflow pipeline pipeline params
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) WithWorkflow(workflow string) *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams {
	o.SetWorkflow(workflow)
	return o
}

// SetWorkflow adds the workflow to the get API v1 info workflow workflow pipeline pipeline params
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) SetWorkflow(workflow string) {
	o.Workflow = workflow
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1InfoWorkflowWorkflowPipelinePipelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	// path param workflow
	if err := r.SetPathParam("workflow", o.Workflow); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
