language: go

sudo: false
dist: trusty
go: 1.13.x

notifications:
  email: false

before_script:
    - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

script:
    - make check_format
    - make build
