language: go

os:
  - linux

sudo: false
dist: bionic
go: 1.13.x

notifications:
  email: false

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

addons:
  apt:
    update: true

script:
  - make check-lint
  - make build
