language: go

os:
  - linux

sudo: false
dist: bionic
go: 1.13.x

notifications:
  email: false

before_install:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
    - go get -u github.com/swaggo/swag/cmd/swag

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

addons:
  apt:
    update: true

script:
  - make check-lint
  - make build
  - make check-api-docs
