site_name: Xene

nav:
  - Home: README.md
  - CmdRef: cmdref/xene.md
  - xenectl: cmdref/xenectl/xenectl.md
  - Design: design/README.md
  - APIDocs: /apidocs.html
  - GoDoc: http://pkg.go.dev/github.com/fristonio/xene

theme: bootstrap4

