site_name: Xene

nav:
  - Home: README.md
  - Architecture: design/README.md
  - APIDocs: /apidocs.html
  - GoDoc: http://pkg.go.dev/github.com/fristonio/xene
  - xene: cmdref/xene.md
  - xenectl: cmdref/xenectl/xenectl.md

theme: bootstrap4

