// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1WebhookTriggerWorkflowPipelinePipelineParams creates a new GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams object
// with the default values initialized.
func NewGetAPIV1WebhookTriggerWorkflowPipelinePipelineParams() *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams {
	var ()
	return &GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1WebhookTriggerWorkflowPipelinePipelineParamsWithTimeout creates a new GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1WebhookTriggerWorkflowPipelinePipelineParamsWithTimeout(timeout time.Duration) *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams {
	var ()
	return &GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams{

		timeout: timeout,
	}
}

// NewGetAPIV1WebhookTriggerWorkflowPipelinePipelineParamsWithContext creates a new GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1WebhookTriggerWorkflowPipelinePipelineParamsWithContext(ctx context.Context) *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams {
	var ()
	return &GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams{

		Context: ctx,
	}
}

// NewGetAPIV1WebhookTriggerWorkflowPipelinePipelineParamsWithHTTPClient creates a new GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1WebhookTriggerWorkflowPipelinePipelineParamsWithHTTPClient(client *http.Client) *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams {
	var ()
	return &GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams{
		HTTPClient: client,
	}
}

/*GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams contains all the parameters to send to the API endpoint
for the get API v1 webhook trigger workflow pipeline pipeline operation typically these are written to a http.Request
*/
type GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams struct {

	/*Pipeline
	  Name of the pipeline to be triggered.

	*/
	Pipeline string
	/*Workflow
	  Name of the workflow.

	*/
	Workflow string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 webhook trigger workflow pipeline pipeline params
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) WithTimeout(timeout time.Duration) *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 webhook trigger workflow pipeline pipeline params
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 webhook trigger workflow pipeline pipeline params
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) WithContext(ctx context.Context) *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 webhook trigger workflow pipeline pipeline params
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 webhook trigger workflow pipeline pipeline params
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) WithHTTPClient(client *http.Client) *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 webhook trigger workflow pipeline pipeline params
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPipeline adds the pipeline to the get API v1 webhook trigger workflow pipeline pipeline params
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) WithPipeline(pipeline string) *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams {
	o.SetPipeline(pipeline)
	return o
}

// SetPipeline adds the pipeline to the get API v1 webhook trigger workflow pipeline pipeline params
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) SetPipeline(pipeline string) {
	o.Pipeline = pipeline
}

// WithWorkflow adds the workflow to the get API v1 webhook trigger workflow pipeline pipeline params
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) WithWorkflow(workflow string) *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams {
	o.SetWorkflow(workflow)
	return o
}

// SetWorkflow adds the workflow to the get API v1 webhook trigger workflow pipeline pipeline params
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) SetWorkflow(workflow string) {
	o.Workflow = workflow
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param pipeline
	if err := r.SetPathParam("pipeline", o.Pipeline); err != nil {
		return err
	}

	// path param workflow
	if err := r.SetPathParam("workflow", o.Workflow); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
