// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new webhook API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for webhook API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetAPIV1WebhookTriggerWorkflowPipelinePipeline(params *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams, authInfo runtime.ClientAuthInfoWriter) error

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetAPIV1WebhookTriggerWorkflowPipelinePipeline webhooks endpoints to trigger the pipelines of a particular workflow
*/
func (a *Client) GetAPIV1WebhookTriggerWorkflowPipelinePipeline(params *GetAPIV1WebhookTriggerWorkflowPipelinePipelineParams, authInfo runtime.ClientAuthInfoWriter) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV1WebhookTriggerWorkflowPipelinePipelineParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetAPIV1WebhookTriggerWorkflowPipelinePipeline",
		Method:             "GET",
		PathPattern:        "/api/v1/webhook/trigger/{workflow}/pipeline/{pipeline}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV1WebhookTriggerWorkflowPipelinePipelineReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
