// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// DeleteAPIV1RegistrySecretNameReader is a Reader for the DeleteAPIV1RegistrySecretName structure.
type DeleteAPIV1RegistrySecretNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV1RegistrySecretNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPIV1RegistrySecretNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAPIV1RegistrySecretNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAPIV1RegistrySecretNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAPIV1RegistrySecretNameOK creates a DeleteAPIV1RegistrySecretNameOK with default headers values
func NewDeleteAPIV1RegistrySecretNameOK() *DeleteAPIV1RegistrySecretNameOK {
	return &DeleteAPIV1RegistrySecretNameOK{}
}

/*DeleteAPIV1RegistrySecretNameOK handles this case with default header values.

OK
*/
type DeleteAPIV1RegistrySecretNameOK struct {
	Payload *models.ResponseHTTPMessage
}

func (o *DeleteAPIV1RegistrySecretNameOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/registry/secret/{name}][%d] deleteApiV1RegistrySecretNameOK  %+v", 200, o.Payload)
}

func (o *DeleteAPIV1RegistrySecretNameOK) GetPayload() *models.ResponseHTTPMessage {
	return o.Payload
}

func (o *DeleteAPIV1RegistrySecretNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIV1RegistrySecretNameBadRequest creates a DeleteAPIV1RegistrySecretNameBadRequest with default headers values
func NewDeleteAPIV1RegistrySecretNameBadRequest() *DeleteAPIV1RegistrySecretNameBadRequest {
	return &DeleteAPIV1RegistrySecretNameBadRequest{}
}

/*DeleteAPIV1RegistrySecretNameBadRequest handles this case with default header values.

Bad Request
*/
type DeleteAPIV1RegistrySecretNameBadRequest struct {
	Payload *models.ResponseHTTPError
}

func (o *DeleteAPIV1RegistrySecretNameBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/registry/secret/{name}][%d] deleteApiV1RegistrySecretNameBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteAPIV1RegistrySecretNameBadRequest) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *DeleteAPIV1RegistrySecretNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIV1RegistrySecretNameInternalServerError creates a DeleteAPIV1RegistrySecretNameInternalServerError with default headers values
func NewDeleteAPIV1RegistrySecretNameInternalServerError() *DeleteAPIV1RegistrySecretNameInternalServerError {
	return &DeleteAPIV1RegistrySecretNameInternalServerError{}
}

/*DeleteAPIV1RegistrySecretNameInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteAPIV1RegistrySecretNameInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *DeleteAPIV1RegistrySecretNameInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/registry/secret/{name}][%d] deleteApiV1RegistrySecretNameInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteAPIV1RegistrySecretNameInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *DeleteAPIV1RegistrySecretNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
