// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIV1RegistryWorkflowNameParams creates a new DeleteAPIV1RegistryWorkflowNameParams object
// with the default values initialized.
func NewDeleteAPIV1RegistryWorkflowNameParams() *DeleteAPIV1RegistryWorkflowNameParams {
	var ()
	return &DeleteAPIV1RegistryWorkflowNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV1RegistryWorkflowNameParamsWithTimeout creates a new DeleteAPIV1RegistryWorkflowNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV1RegistryWorkflowNameParamsWithTimeout(timeout time.Duration) *DeleteAPIV1RegistryWorkflowNameParams {
	var ()
	return &DeleteAPIV1RegistryWorkflowNameParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV1RegistryWorkflowNameParamsWithContext creates a new DeleteAPIV1RegistryWorkflowNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV1RegistryWorkflowNameParamsWithContext(ctx context.Context) *DeleteAPIV1RegistryWorkflowNameParams {
	var ()
	return &DeleteAPIV1RegistryWorkflowNameParams{

		Context: ctx,
	}
}

// NewDeleteAPIV1RegistryWorkflowNameParamsWithHTTPClient creates a new DeleteAPIV1RegistryWorkflowNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV1RegistryWorkflowNameParamsWithHTTPClient(client *http.Client) *DeleteAPIV1RegistryWorkflowNameParams {
	var ()
	return &DeleteAPIV1RegistryWorkflowNameParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV1RegistryWorkflowNameParams contains all the parameters to send to the API endpoint
for the delete API v1 registry workflow name operation typically these are written to a http.Request
*/
type DeleteAPIV1RegistryWorkflowNameParams struct {

	/*Name
	  Name of the workflow to be deleted.

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API v1 registry workflow name params
func (o *DeleteAPIV1RegistryWorkflowNameParams) WithTimeout(timeout time.Duration) *DeleteAPIV1RegistryWorkflowNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v1 registry workflow name params
func (o *DeleteAPIV1RegistryWorkflowNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v1 registry workflow name params
func (o *DeleteAPIV1RegistryWorkflowNameParams) WithContext(ctx context.Context) *DeleteAPIV1RegistryWorkflowNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v1 registry workflow name params
func (o *DeleteAPIV1RegistryWorkflowNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v1 registry workflow name params
func (o *DeleteAPIV1RegistryWorkflowNameParams) WithHTTPClient(client *http.Client) *DeleteAPIV1RegistryWorkflowNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v1 registry workflow name params
func (o *DeleteAPIV1RegistryWorkflowNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete API v1 registry workflow name params
func (o *DeleteAPIV1RegistryWorkflowNameParams) WithName(name string) *DeleteAPIV1RegistryWorkflowNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete API v1 registry workflow name params
func (o *DeleteAPIV1RegistryWorkflowNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV1RegistryWorkflowNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
