// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIV1RegistrySecretNameParams creates a new DeleteAPIV1RegistrySecretNameParams object
// with the default values initialized.
func NewDeleteAPIV1RegistrySecretNameParams() *DeleteAPIV1RegistrySecretNameParams {
	var ()
	return &DeleteAPIV1RegistrySecretNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV1RegistrySecretNameParamsWithTimeout creates a new DeleteAPIV1RegistrySecretNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV1RegistrySecretNameParamsWithTimeout(timeout time.Duration) *DeleteAPIV1RegistrySecretNameParams {
	var ()
	return &DeleteAPIV1RegistrySecretNameParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV1RegistrySecretNameParamsWithContext creates a new DeleteAPIV1RegistrySecretNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV1RegistrySecretNameParamsWithContext(ctx context.Context) *DeleteAPIV1RegistrySecretNameParams {
	var ()
	return &DeleteAPIV1RegistrySecretNameParams{

		Context: ctx,
	}
}

// NewDeleteAPIV1RegistrySecretNameParamsWithHTTPClient creates a new DeleteAPIV1RegistrySecretNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV1RegistrySecretNameParamsWithHTTPClient(client *http.Client) *DeleteAPIV1RegistrySecretNameParams {
	var ()
	return &DeleteAPIV1RegistrySecretNameParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV1RegistrySecretNameParams contains all the parameters to send to the API endpoint
for the delete API v1 registry secret name operation typically these are written to a http.Request
*/
type DeleteAPIV1RegistrySecretNameParams struct {

	/*Name
	  Name of the secret to be deleted.

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete API v1 registry secret name params
func (o *DeleteAPIV1RegistrySecretNameParams) WithTimeout(timeout time.Duration) *DeleteAPIV1RegistrySecretNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v1 registry secret name params
func (o *DeleteAPIV1RegistrySecretNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v1 registry secret name params
func (o *DeleteAPIV1RegistrySecretNameParams) WithContext(ctx context.Context) *DeleteAPIV1RegistrySecretNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v1 registry secret name params
func (o *DeleteAPIV1RegistrySecretNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v1 registry secret name params
func (o *DeleteAPIV1RegistrySecretNameParams) WithHTTPClient(client *http.Client) *DeleteAPIV1RegistrySecretNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v1 registry secret name params
func (o *DeleteAPIV1RegistrySecretNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete API v1 registry secret name params
func (o *DeleteAPIV1RegistrySecretNameParams) WithName(name string) *DeleteAPIV1RegistrySecretNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete API v1 registry secret name params
func (o *DeleteAPIV1RegistrySecretNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV1RegistrySecretNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
