// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1RegistryListRegitemParams creates a new GetAPIV1RegistryListRegitemParams object
// with the default values initialized.
func NewGetAPIV1RegistryListRegitemParams() *GetAPIV1RegistryListRegitemParams {
	var ()
	return &GetAPIV1RegistryListRegitemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1RegistryListRegitemParamsWithTimeout creates a new GetAPIV1RegistryListRegitemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1RegistryListRegitemParamsWithTimeout(timeout time.Duration) *GetAPIV1RegistryListRegitemParams {
	var ()
	return &GetAPIV1RegistryListRegitemParams{

		timeout: timeout,
	}
}

// NewGetAPIV1RegistryListRegitemParamsWithContext creates a new GetAPIV1RegistryListRegitemParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1RegistryListRegitemParamsWithContext(ctx context.Context) *GetAPIV1RegistryListRegitemParams {
	var ()
	return &GetAPIV1RegistryListRegitemParams{

		Context: ctx,
	}
}

// NewGetAPIV1RegistryListRegitemParamsWithHTTPClient creates a new GetAPIV1RegistryListRegitemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1RegistryListRegitemParamsWithHTTPClient(client *http.Client) *GetAPIV1RegistryListRegitemParams {
	var ()
	return &GetAPIV1RegistryListRegitemParams{
		HTTPClient: client,
	}
}

/*GetAPIV1RegistryListRegitemParams contains all the parameters to send to the API endpoint
for the get API v1 registry list regitem operation typically these are written to a http.Request
*/
type GetAPIV1RegistryListRegitemParams struct {

	/*Regitem
	  RegistryItem type for the listing.

	*/
	Regitem string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 registry list regitem params
func (o *GetAPIV1RegistryListRegitemParams) WithTimeout(timeout time.Duration) *GetAPIV1RegistryListRegitemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 registry list regitem params
func (o *GetAPIV1RegistryListRegitemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 registry list regitem params
func (o *GetAPIV1RegistryListRegitemParams) WithContext(ctx context.Context) *GetAPIV1RegistryListRegitemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 registry list regitem params
func (o *GetAPIV1RegistryListRegitemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 registry list regitem params
func (o *GetAPIV1RegistryListRegitemParams) WithHTTPClient(client *http.Client) *GetAPIV1RegistryListRegitemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 registry list regitem params
func (o *GetAPIV1RegistryListRegitemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRegitem adds the regitem to the get API v1 registry list regitem params
func (o *GetAPIV1RegistryListRegitemParams) WithRegitem(regitem string) *GetAPIV1RegistryListRegitemParams {
	o.SetRegitem(regitem)
	return o
}

// SetRegitem adds the regitem to the get API v1 registry list regitem params
func (o *GetAPIV1RegistryListRegitemParams) SetRegitem(regitem string) {
	o.Regitem = regitem
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1RegistryListRegitemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param regitem
	if err := r.SetPathParam("regitem", o.Regitem); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
