// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetAPIV1RegistryWorkflowNameReader is a Reader for the GetAPIV1RegistryWorkflowName structure.
type GetAPIV1RegistryWorkflowNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1RegistryWorkflowNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1RegistryWorkflowNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAPIV1RegistryWorkflowNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV1RegistryWorkflowNameOK creates a GetAPIV1RegistryWorkflowNameOK with default headers values
func NewGetAPIV1RegistryWorkflowNameOK() *GetAPIV1RegistryWorkflowNameOK {
	return &GetAPIV1RegistryWorkflowNameOK{}
}

/*GetAPIV1RegistryWorkflowNameOK handles this case with default header values.

OK
*/
type GetAPIV1RegistryWorkflowNameOK struct {
	Payload *models.ResponseRegistryItem
}

func (o *GetAPIV1RegistryWorkflowNameOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/registry/workflow/{name}][%d] getApiV1RegistryWorkflowNameOK  %+v", 200, o.Payload)
}

func (o *GetAPIV1RegistryWorkflowNameOK) GetPayload() *models.ResponseRegistryItem {
	return o.Payload
}

func (o *GetAPIV1RegistryWorkflowNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseRegistryItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1RegistryWorkflowNameInternalServerError creates a GetAPIV1RegistryWorkflowNameInternalServerError with default headers values
func NewGetAPIV1RegistryWorkflowNameInternalServerError() *GetAPIV1RegistryWorkflowNameInternalServerError {
	return &GetAPIV1RegistryWorkflowNameInternalServerError{}
}

/*GetAPIV1RegistryWorkflowNameInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIV1RegistryWorkflowNameInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *GetAPIV1RegistryWorkflowNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/registry/workflow/{name}][%d] getApiV1RegistryWorkflowNameInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPIV1RegistryWorkflowNameInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetAPIV1RegistryWorkflowNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
