// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetAPIV1RegistryWorkflowReader is a Reader for the GetAPIV1RegistryWorkflow structure.
type GetAPIV1RegistryWorkflowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1RegistryWorkflowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1RegistryWorkflowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAPIV1RegistryWorkflowInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV1RegistryWorkflowOK creates a GetAPIV1RegistryWorkflowOK with default headers values
func NewGetAPIV1RegistryWorkflowOK() *GetAPIV1RegistryWorkflowOK {
	return &GetAPIV1RegistryWorkflowOK{}
}

/*GetAPIV1RegistryWorkflowOK handles this case with default header values.

OK
*/
type GetAPIV1RegistryWorkflowOK struct {
	Payload *models.ResponseRegistryItem
}

func (o *GetAPIV1RegistryWorkflowOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/registry/workflow][%d] getApiV1RegistryWorkflowOK  %+v", 200, o.Payload)
}

func (o *GetAPIV1RegistryWorkflowOK) GetPayload() *models.ResponseRegistryItem {
	return o.Payload
}

func (o *GetAPIV1RegistryWorkflowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseRegistryItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1RegistryWorkflowInternalServerError creates a GetAPIV1RegistryWorkflowInternalServerError with default headers values
func NewGetAPIV1RegistryWorkflowInternalServerError() *GetAPIV1RegistryWorkflowInternalServerError {
	return &GetAPIV1RegistryWorkflowInternalServerError{}
}

/*GetAPIV1RegistryWorkflowInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIV1RegistryWorkflowInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *GetAPIV1RegistryWorkflowInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/registry/workflow][%d] getApiV1RegistryWorkflowInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPIV1RegistryWorkflowInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetAPIV1RegistryWorkflowInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
