// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1RegistrySecretNameParams creates a new GetAPIV1RegistrySecretNameParams object
// with the default values initialized.
func NewGetAPIV1RegistrySecretNameParams() *GetAPIV1RegistrySecretNameParams {
	var ()
	return &GetAPIV1RegistrySecretNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1RegistrySecretNameParamsWithTimeout creates a new GetAPIV1RegistrySecretNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1RegistrySecretNameParamsWithTimeout(timeout time.Duration) *GetAPIV1RegistrySecretNameParams {
	var ()
	return &GetAPIV1RegistrySecretNameParams{

		timeout: timeout,
	}
}

// NewGetAPIV1RegistrySecretNameParamsWithContext creates a new GetAPIV1RegistrySecretNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1RegistrySecretNameParamsWithContext(ctx context.Context) *GetAPIV1RegistrySecretNameParams {
	var ()
	return &GetAPIV1RegistrySecretNameParams{

		Context: ctx,
	}
}

// NewGetAPIV1RegistrySecretNameParamsWithHTTPClient creates a new GetAPIV1RegistrySecretNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1RegistrySecretNameParamsWithHTTPClient(client *http.Client) *GetAPIV1RegistrySecretNameParams {
	var ()
	return &GetAPIV1RegistrySecretNameParams{
		HTTPClient: client,
	}
}

/*GetAPIV1RegistrySecretNameParams contains all the parameters to send to the API endpoint
for the get API v1 registry secret name operation typically these are written to a http.Request
*/
type GetAPIV1RegistrySecretNameParams struct {

	/*Name
	  name of the secret to get.

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 registry secret name params
func (o *GetAPIV1RegistrySecretNameParams) WithTimeout(timeout time.Duration) *GetAPIV1RegistrySecretNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 registry secret name params
func (o *GetAPIV1RegistrySecretNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 registry secret name params
func (o *GetAPIV1RegistrySecretNameParams) WithContext(ctx context.Context) *GetAPIV1RegistrySecretNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 registry secret name params
func (o *GetAPIV1RegistrySecretNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 registry secret name params
func (o *GetAPIV1RegistrySecretNameParams) WithHTTPClient(client *http.Client) *GetAPIV1RegistrySecretNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 registry secret name params
func (o *GetAPIV1RegistrySecretNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get API v1 registry secret name params
func (o *GetAPIV1RegistrySecretNameParams) WithName(name string) *GetAPIV1RegistrySecretNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get API v1 registry secret name params
func (o *GetAPIV1RegistrySecretNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1RegistrySecretNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
