// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1InfoWorkflowNameParams creates a new GetAPIV1InfoWorkflowNameParams object
// with the default values initialized.
func NewGetAPIV1InfoWorkflowNameParams() *GetAPIV1InfoWorkflowNameParams {
	var ()
	return &GetAPIV1InfoWorkflowNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1InfoWorkflowNameParamsWithTimeout creates a new GetAPIV1InfoWorkflowNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1InfoWorkflowNameParamsWithTimeout(timeout time.Duration) *GetAPIV1InfoWorkflowNameParams {
	var ()
	return &GetAPIV1InfoWorkflowNameParams{

		timeout: timeout,
	}
}

// NewGetAPIV1InfoWorkflowNameParamsWithContext creates a new GetAPIV1InfoWorkflowNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1InfoWorkflowNameParamsWithContext(ctx context.Context) *GetAPIV1InfoWorkflowNameParams {
	var ()
	return &GetAPIV1InfoWorkflowNameParams{

		Context: ctx,
	}
}

// NewGetAPIV1InfoWorkflowNameParamsWithHTTPClient creates a new GetAPIV1InfoWorkflowNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1InfoWorkflowNameParamsWithHTTPClient(client *http.Client) *GetAPIV1InfoWorkflowNameParams {
	var ()
	return &GetAPIV1InfoWorkflowNameParams{
		HTTPClient: client,
	}
}

/*GetAPIV1InfoWorkflowNameParams contains all the parameters to send to the API endpoint
for the get API v1 info workflow name operation typically these are written to a http.Request
*/
type GetAPIV1InfoWorkflowNameParams struct {

	/*Name
	  Name of the workflow to get information about.

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 info workflow name params
func (o *GetAPIV1InfoWorkflowNameParams) WithTimeout(timeout time.Duration) *GetAPIV1InfoWorkflowNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 info workflow name params
func (o *GetAPIV1InfoWorkflowNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 info workflow name params
func (o *GetAPIV1InfoWorkflowNameParams) WithContext(ctx context.Context) *GetAPIV1InfoWorkflowNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 info workflow name params
func (o *GetAPIV1InfoWorkflowNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 info workflow name params
func (o *GetAPIV1InfoWorkflowNameParams) WithHTTPClient(client *http.Client) *GetAPIV1InfoWorkflowNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 info workflow name params
func (o *GetAPIV1InfoWorkflowNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get API v1 info workflow name params
func (o *GetAPIV1InfoWorkflowNameParams) WithName(name string) *GetAPIV1InfoWorkflowNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get API v1 info workflow name params
func (o *GetAPIV1InfoWorkflowNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1InfoWorkflowNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
