// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetAPIV1RegistrySecretNameReader is a Reader for the GetAPIV1RegistrySecretName structure.
type GetAPIV1RegistrySecretNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1RegistrySecretNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1RegistrySecretNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAPIV1RegistrySecretNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV1RegistrySecretNameOK creates a GetAPIV1RegistrySecretNameOK with default headers values
func NewGetAPIV1RegistrySecretNameOK() *GetAPIV1RegistrySecretNameOK {
	return &GetAPIV1RegistrySecretNameOK{}
}

/*GetAPIV1RegistrySecretNameOK handles this case with default header values.

OK
*/
type GetAPIV1RegistrySecretNameOK struct {
	Payload *models.ResponseRegistryItem
}

func (o *GetAPIV1RegistrySecretNameOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/registry/secret/{name}][%d] getApiV1RegistrySecretNameOK  %+v", 200, o.Payload)
}

func (o *GetAPIV1RegistrySecretNameOK) GetPayload() *models.ResponseRegistryItem {
	return o.Payload
}

func (o *GetAPIV1RegistrySecretNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseRegistryItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1RegistrySecretNameInternalServerError creates a GetAPIV1RegistrySecretNameInternalServerError with default headers values
func NewGetAPIV1RegistrySecretNameInternalServerError() *GetAPIV1RegistrySecretNameInternalServerError {
	return &GetAPIV1RegistrySecretNameInternalServerError{}
}

/*GetAPIV1RegistrySecretNameInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIV1RegistrySecretNameInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *GetAPIV1RegistrySecretNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/registry/secret/{name}][%d] getApiV1RegistrySecretNameInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPIV1RegistrySecretNameInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetAPIV1RegistrySecretNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
