// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetAPIV1RegistryListSecretsReader is a Reader for the GetAPIV1RegistryListSecrets structure.
type GetAPIV1RegistryListSecretsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1RegistryListSecretsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1RegistryListSecretsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV1RegistryListSecretsOK creates a GetAPIV1RegistryListSecretsOK with default headers values
func NewGetAPIV1RegistryListSecretsOK() *GetAPIV1RegistryListSecretsOK {
	return &GetAPIV1RegistryListSecretsOK{}
}

/*GetAPIV1RegistryListSecretsOK handles this case with default header values.

OK
*/
type GetAPIV1RegistryListSecretsOK struct {
	Payload []*models.ResponseSecretInfo
}

func (o *GetAPIV1RegistryListSecretsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/registry/list/secrets][%d] getApiV1RegistryListSecretsOK  %+v", 200, o.Payload)
}

func (o *GetAPIV1RegistryListSecretsOK) GetPayload() []*models.ResponseSecretInfo {
	return o.Payload
}

func (o *GetAPIV1RegistryListSecretsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
