// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetAPIV1RegistrySecretReader is a Reader for the GetAPIV1RegistrySecret structure.
type GetAPIV1RegistrySecretReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1RegistrySecretReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1RegistrySecretOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAPIV1RegistrySecretInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV1RegistrySecretOK creates a GetAPIV1RegistrySecretOK with default headers values
func NewGetAPIV1RegistrySecretOK() *GetAPIV1RegistrySecretOK {
	return &GetAPIV1RegistrySecretOK{}
}

/*GetAPIV1RegistrySecretOK handles this case with default header values.

OK
*/
type GetAPIV1RegistrySecretOK struct {
	Payload *models.ResponseRegistryItem
}

func (o *GetAPIV1RegistrySecretOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/registry/secret][%d] getApiV1RegistrySecretOK  %+v", 200, o.Payload)
}

func (o *GetAPIV1RegistrySecretOK) GetPayload() *models.ResponseRegistryItem {
	return o.Payload
}

func (o *GetAPIV1RegistrySecretOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseRegistryItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAPIV1RegistrySecretInternalServerError creates a GetAPIV1RegistrySecretInternalServerError with default headers values
func NewGetAPIV1RegistrySecretInternalServerError() *GetAPIV1RegistrySecretInternalServerError {
	return &GetAPIV1RegistrySecretInternalServerError{}
}

/*GetAPIV1RegistrySecretInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAPIV1RegistrySecretInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *GetAPIV1RegistrySecretInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/registry/secret][%d] getApiV1RegistrySecretInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAPIV1RegistrySecretInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetAPIV1RegistrySecretInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
