// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1RegistryListWorkflowsParams creates a new GetAPIV1RegistryListWorkflowsParams object
// with the default values initialized.
func NewGetAPIV1RegistryListWorkflowsParams() *GetAPIV1RegistryListWorkflowsParams {

	return &GetAPIV1RegistryListWorkflowsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1RegistryListWorkflowsParamsWithTimeout creates a new GetAPIV1RegistryListWorkflowsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1RegistryListWorkflowsParamsWithTimeout(timeout time.Duration) *GetAPIV1RegistryListWorkflowsParams {

	return &GetAPIV1RegistryListWorkflowsParams{

		timeout: timeout,
	}
}

// NewGetAPIV1RegistryListWorkflowsParamsWithContext creates a new GetAPIV1RegistryListWorkflowsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1RegistryListWorkflowsParamsWithContext(ctx context.Context) *GetAPIV1RegistryListWorkflowsParams {

	return &GetAPIV1RegistryListWorkflowsParams{

		Context: ctx,
	}
}

// NewGetAPIV1RegistryListWorkflowsParamsWithHTTPClient creates a new GetAPIV1RegistryListWorkflowsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1RegistryListWorkflowsParamsWithHTTPClient(client *http.Client) *GetAPIV1RegistryListWorkflowsParams {

	return &GetAPIV1RegistryListWorkflowsParams{
		HTTPClient: client,
	}
}

/*GetAPIV1RegistryListWorkflowsParams contains all the parameters to send to the API endpoint
for the get API v1 registry list workflows operation typically these are written to a http.Request
*/
type GetAPIV1RegistryListWorkflowsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 registry list workflows params
func (o *GetAPIV1RegistryListWorkflowsParams) WithTimeout(timeout time.Duration) *GetAPIV1RegistryListWorkflowsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 registry list workflows params
func (o *GetAPIV1RegistryListWorkflowsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 registry list workflows params
func (o *GetAPIV1RegistryListWorkflowsParams) WithContext(ctx context.Context) *GetAPIV1RegistryListWorkflowsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 registry list workflows params
func (o *GetAPIV1RegistryListWorkflowsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 registry list workflows params
func (o *GetAPIV1RegistryListWorkflowsParams) WithHTTPClient(client *http.Client) *GetAPIV1RegistryListWorkflowsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 registry list workflows params
func (o *GetAPIV1RegistryListWorkflowsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1RegistryListWorkflowsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
