// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1RegistryListSecretsParams creates a new GetAPIV1RegistryListSecretsParams object
// with the default values initialized.
func NewGetAPIV1RegistryListSecretsParams() *GetAPIV1RegistryListSecretsParams {

	return &GetAPIV1RegistryListSecretsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1RegistryListSecretsParamsWithTimeout creates a new GetAPIV1RegistryListSecretsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1RegistryListSecretsParamsWithTimeout(timeout time.Duration) *GetAPIV1RegistryListSecretsParams {

	return &GetAPIV1RegistryListSecretsParams{

		timeout: timeout,
	}
}

// NewGetAPIV1RegistryListSecretsParamsWithContext creates a new GetAPIV1RegistryListSecretsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1RegistryListSecretsParamsWithContext(ctx context.Context) *GetAPIV1RegistryListSecretsParams {

	return &GetAPIV1RegistryListSecretsParams{

		Context: ctx,
	}
}

// NewGetAPIV1RegistryListSecretsParamsWithHTTPClient creates a new GetAPIV1RegistryListSecretsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1RegistryListSecretsParamsWithHTTPClient(client *http.Client) *GetAPIV1RegistryListSecretsParams {

	return &GetAPIV1RegistryListSecretsParams{
		HTTPClient: client,
	}
}

/*GetAPIV1RegistryListSecretsParams contains all the parameters to send to the API endpoint
for the get API v1 registry list secrets operation typically these are written to a http.Request
*/
type GetAPIV1RegistryListSecretsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 registry list secrets params
func (o *GetAPIV1RegistryListSecretsParams) WithTimeout(timeout time.Duration) *GetAPIV1RegistryListSecretsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 registry list secrets params
func (o *GetAPIV1RegistryListSecretsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 registry list secrets params
func (o *GetAPIV1RegistryListSecretsParams) WithContext(ctx context.Context) *GetAPIV1RegistryListSecretsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 registry list secrets params
func (o *GetAPIV1RegistryListSecretsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 registry list secrets params
func (o *GetAPIV1RegistryListSecretsParams) WithHTTPClient(client *http.Client) *GetAPIV1RegistryListSecretsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 registry list secrets params
func (o *GetAPIV1RegistryListSecretsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1RegistryListSecretsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
