// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1RegistryListAgentsParams creates a new GetAPIV1RegistryListAgentsParams object
// with the default values initialized.
func NewGetAPIV1RegistryListAgentsParams() *GetAPIV1RegistryListAgentsParams {

	return &GetAPIV1RegistryListAgentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1RegistryListAgentsParamsWithTimeout creates a new GetAPIV1RegistryListAgentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1RegistryListAgentsParamsWithTimeout(timeout time.Duration) *GetAPIV1RegistryListAgentsParams {

	return &GetAPIV1RegistryListAgentsParams{

		timeout: timeout,
	}
}

// NewGetAPIV1RegistryListAgentsParamsWithContext creates a new GetAPIV1RegistryListAgentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1RegistryListAgentsParamsWithContext(ctx context.Context) *GetAPIV1RegistryListAgentsParams {

	return &GetAPIV1RegistryListAgentsParams{

		Context: ctx,
	}
}

// NewGetAPIV1RegistryListAgentsParamsWithHTTPClient creates a new GetAPIV1RegistryListAgentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1RegistryListAgentsParamsWithHTTPClient(client *http.Client) *GetAPIV1RegistryListAgentsParams {

	return &GetAPIV1RegistryListAgentsParams{
		HTTPClient: client,
	}
}

/*GetAPIV1RegistryListAgentsParams contains all the parameters to send to the API endpoint
for the get API v1 registry list agents operation typically these are written to a http.Request
*/
type GetAPIV1RegistryListAgentsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 registry list agents params
func (o *GetAPIV1RegistryListAgentsParams) WithTimeout(timeout time.Duration) *GetAPIV1RegistryListAgentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 registry list agents params
func (o *GetAPIV1RegistryListAgentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 registry list agents params
func (o *GetAPIV1RegistryListAgentsParams) WithContext(ctx context.Context) *GetAPIV1RegistryListAgentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 registry list agents params
func (o *GetAPIV1RegistryListAgentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 registry list agents params
func (o *GetAPIV1RegistryListAgentsParams) WithHTTPClient(client *http.Client) *GetAPIV1RegistryListAgentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 registry list agents params
func (o *GetAPIV1RegistryListAgentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1RegistryListAgentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
