// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchAPIV1RegistrySecretNameParams creates a new PatchAPIV1RegistrySecretNameParams object
// with the default values initialized.
func NewPatchAPIV1RegistrySecretNameParams() *PatchAPIV1RegistrySecretNameParams {
	var ()
	return &PatchAPIV1RegistrySecretNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPIV1RegistrySecretNameParamsWithTimeout creates a new PatchAPIV1RegistrySecretNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchAPIV1RegistrySecretNameParamsWithTimeout(timeout time.Duration) *PatchAPIV1RegistrySecretNameParams {
	var ()
	return &PatchAPIV1RegistrySecretNameParams{

		timeout: timeout,
	}
}

// NewPatchAPIV1RegistrySecretNameParamsWithContext creates a new PatchAPIV1RegistrySecretNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchAPIV1RegistrySecretNameParamsWithContext(ctx context.Context) *PatchAPIV1RegistrySecretNameParams {
	var ()
	return &PatchAPIV1RegistrySecretNameParams{

		Context: ctx,
	}
}

// NewPatchAPIV1RegistrySecretNameParamsWithHTTPClient creates a new PatchAPIV1RegistrySecretNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchAPIV1RegistrySecretNameParamsWithHTTPClient(client *http.Client) *PatchAPIV1RegistrySecretNameParams {
	var ()
	return &PatchAPIV1RegistrySecretNameParams{
		HTTPClient: client,
	}
}

/*PatchAPIV1RegistrySecretNameParams contains all the parameters to send to the API endpoint
for the patch API v1 registry secret name operation typically these are written to a http.Request
*/
type PatchAPIV1RegistrySecretNameParams struct {

	/*Name
	  Name of the secret to be patched.

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch API v1 registry secret name params
func (o *PatchAPIV1RegistrySecretNameParams) WithTimeout(timeout time.Duration) *PatchAPIV1RegistrySecretNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API v1 registry secret name params
func (o *PatchAPIV1RegistrySecretNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API v1 registry secret name params
func (o *PatchAPIV1RegistrySecretNameParams) WithContext(ctx context.Context) *PatchAPIV1RegistrySecretNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API v1 registry secret name params
func (o *PatchAPIV1RegistrySecretNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API v1 registry secret name params
func (o *PatchAPIV1RegistrySecretNameParams) WithHTTPClient(client *http.Client) *PatchAPIV1RegistrySecretNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API v1 registry secret name params
func (o *PatchAPIV1RegistrySecretNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the patch API v1 registry secret name params
func (o *PatchAPIV1RegistrySecretNameParams) WithName(name string) *PatchAPIV1RegistrySecretNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the patch API v1 registry secret name params
func (o *PatchAPIV1RegistrySecretNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPIV1RegistrySecretNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
