// Code generated by go-swagger; DO NOT EDIT.

package registry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// PostAPIV1RegistryWorkflowReader is a Reader for the PostAPIV1RegistryWorkflow structure.
type PostAPIV1RegistryWorkflowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1RegistryWorkflowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1RegistryWorkflowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1RegistryWorkflowBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1RegistryWorkflowInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV1RegistryWorkflowOK creates a PostAPIV1RegistryWorkflowOK with default headers values
func NewPostAPIV1RegistryWorkflowOK() *PostAPIV1RegistryWorkflowOK {
	return &PostAPIV1RegistryWorkflowOK{}
}

/*PostAPIV1RegistryWorkflowOK handles this case with default header values.

OK
*/
type PostAPIV1RegistryWorkflowOK struct {
	Payload *models.ResponseHTTPMessage
}

func (o *PostAPIV1RegistryWorkflowOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/registry/workflow][%d] postApiV1RegistryWorkflowOK  %+v", 200, o.Payload)
}

func (o *PostAPIV1RegistryWorkflowOK) GetPayload() *models.ResponseHTTPMessage {
	return o.Payload
}

func (o *PostAPIV1RegistryWorkflowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1RegistryWorkflowBadRequest creates a PostAPIV1RegistryWorkflowBadRequest with default headers values
func NewPostAPIV1RegistryWorkflowBadRequest() *PostAPIV1RegistryWorkflowBadRequest {
	return &PostAPIV1RegistryWorkflowBadRequest{}
}

/*PostAPIV1RegistryWorkflowBadRequest handles this case with default header values.

Bad Request
*/
type PostAPIV1RegistryWorkflowBadRequest struct {
	Payload *models.ResponseHTTPError
}

func (o *PostAPIV1RegistryWorkflowBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/registry/workflow][%d] postApiV1RegistryWorkflowBadRequest  %+v", 400, o.Payload)
}

func (o *PostAPIV1RegistryWorkflowBadRequest) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *PostAPIV1RegistryWorkflowBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1RegistryWorkflowInternalServerError creates a PostAPIV1RegistryWorkflowInternalServerError with default headers values
func NewPostAPIV1RegistryWorkflowInternalServerError() *PostAPIV1RegistryWorkflowInternalServerError {
	return &PostAPIV1RegistryWorkflowInternalServerError{}
}

/*PostAPIV1RegistryWorkflowInternalServerError handles this case with default header values.

Internal Server Error
*/
type PostAPIV1RegistryWorkflowInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *PostAPIV1RegistryWorkflowInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/registry/workflow][%d] postApiV1RegistryWorkflowInternalServerError  %+v", 500, o.Payload)
}

func (o *PostAPIV1RegistryWorkflowInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *PostAPIV1RegistryWorkflowInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
