// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1AuthokParams creates a new GetAPIV1AuthokParams object
// with the default values initialized.
func NewGetAPIV1AuthokParams() *GetAPIV1AuthokParams {

	return &GetAPIV1AuthokParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1AuthokParamsWithTimeout creates a new GetAPIV1AuthokParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV1AuthokParamsWithTimeout(timeout time.Duration) *GetAPIV1AuthokParams {

	return &GetAPIV1AuthokParams{

		timeout: timeout,
	}
}

// NewGetAPIV1AuthokParamsWithContext creates a new GetAPIV1AuthokParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV1AuthokParamsWithContext(ctx context.Context) *GetAPIV1AuthokParams {

	return &GetAPIV1AuthokParams{

		Context: ctx,
	}
}

// NewGetAPIV1AuthokParamsWithHTTPClient creates a new GetAPIV1AuthokParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV1AuthokParamsWithHTTPClient(client *http.Client) *GetAPIV1AuthokParams {

	return &GetAPIV1AuthokParams{
		HTTPClient: client,
	}
}

/*GetAPIV1AuthokParams contains all the parameters to send to the API endpoint
for the get API v1 authok operation typically these are written to a http.Request
*/
type GetAPIV1AuthokParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get API v1 authok params
func (o *GetAPIV1AuthokParams) WithTimeout(timeout time.Duration) *GetAPIV1AuthokParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 authok params
func (o *GetAPIV1AuthokParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 authok params
func (o *GetAPIV1AuthokParams) WithContext(ctx context.Context) *GetAPIV1AuthokParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 authok params
func (o *GetAPIV1AuthokParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 authok params
func (o *GetAPIV1AuthokParams) WithHTTPClient(client *http.Client) *GetAPIV1AuthokParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 authok params
func (o *GetAPIV1AuthokParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1AuthokParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
