# Agent Configuration
agent:
    # Name contains the name of the agent
    name: default.agent.xene

    # Host to run the Agent on
    host: "0.0.0.0"

    # Address of the API server, make sure that the APIServer is reachable
    # from the agent.
    apiServer: "http://0.0.0.0:6060"

    # Auth Token to use when registrering with the APIServer.
    apiAuthToken: "xxx"

    # Address of the agent.
    address: "http://0.0.0.0:6061"

    # Whether to run Xene in insecure mode with no authentication.
    insecure: false

    # Server Name of the agent for mTLS between APIServer and agent.
    serverName: agent.xene.io

    # Parameters for running a sercure cluster, make sure these are correct
    # certificates.
    keyFile: /etc/xene/certs/server.gen/server-key.pem
    certFile: /etc/xene/certs/server.gen/server.pem
    rootCACert: /etc/xene/certs/ca.gen/ca.pem
    clientKeyFile: /etc/xene/certs/client.gen/client-key.pem
    clientCertFile: /etc/xene/certs/client.gen/client.pem
