apiserver:
    host: "127.0.0.1"
    verboseLogs: true
    jwtSecret: "xxxxx"
    allowedDomains:
      - "ec.iitr.ac.in"
    oauth:
        google:
            name: google
            clientID: "xxxx.apps.googleusercontent.com"
            clientSecret: "xxxx"
            redirectURL: "http://localhost:3000/oauth/callback"
            scopes:
                - profile
                - email
