// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsePipelineRunVerboseInfo response pipeline run verbose info
//
// swagger:model response.PipelineRunVerboseInfo
type ResponsePipelineRunVerboseInfo struct {

	// base log URL
	BaseLogURL string `json:"baseLogURL,omitempty"`

	// run ID
	RunID string `json:"runID,omitempty"`

	// run info
	RunInfo string `json:"runInfo,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this response pipeline run verbose info
func (m *ResponsePipelineRunVerboseInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsePipelineRunVerboseInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsePipelineRunVerboseInfo) UnmarshalBinary(b []byte) error {
	var res ResponsePipelineRunVerboseInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
