// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponseRegistryItem response registry item
//
// swagger:model response.RegistryItem
type ResponseRegistryItem struct {

	// item
	Item string `json:"item,omitempty"`
}

// Validate validates this response registry item
func (m *ResponseRegistryItem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseRegistryItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseRegistryItem) UnmarshalBinary(b []byte) error {
	var res ResponseRegistryItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
