// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponseWorkflowInfo response workflow info
//
// swagger:model response.WorkflowInfo
type ResponseWorkflowInfo struct {

	// agents
	Agents []string `json:"agents"`

	// name
	Name string `json:"name,omitempty"`

	// pipelines
	Pipelines []string `json:"pipelines"`

	// triggers
	Triggers []string `json:"triggers"`
}

// Validate validates this response workflow info
func (m *ResponseWorkflowInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseWorkflowInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseWorkflowInfo) UnmarshalBinary(b []byte) error {
	var res ResponseWorkflowInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
