// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponseJWTAuth response j w t auth
//
// swagger:model response.JWTAuth
type ResponseJWTAuth struct {

	// expires in
	ExpiresIn string `json:"expiresIn,omitempty"`

	// token
	Token string `json:"token,omitempty"`

	// user email
	UserEmail string `json:"userEmail,omitempty"`

	// user name
	UserName string `json:"userName,omitempty"`
}

// Validate validates this response j w t auth
func (m *ResponseJWTAuth) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseJWTAuth) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseJWTAuth) UnmarshalBinary(b []byte) error {
	var res ResponseJWTAuth
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
