// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponseAgentTriggerInfo response agent trigger info
//
// swagger:model response.AgentTriggerInfo
type ResponseAgentTriggerInfo struct {

	// name
	Name string `json:"name,omitempty"`

	// pipelines
	Pipelines []string `json:"pipelines"`
}

// Validate validates this response agent trigger info
func (m *ResponseAgentTriggerInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseAgentTriggerInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseAgentTriggerInfo) UnmarshalBinary(b []byte) error {
	var res ResponseAgentTriggerInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
