// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOauthRefreshParams creates a new GetOauthRefreshParams object
// with the default values initialized.
func NewGetOauthRefreshParams() *GetOauthRefreshParams {

	return &GetOauthRefreshParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOauthRefreshParamsWithTimeout creates a new GetOauthRefreshParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOauthRefreshParamsWithTimeout(timeout time.Duration) *GetOauthRefreshParams {

	return &GetOauthRefreshParams{

		timeout: timeout,
	}
}

// NewGetOauthRefreshParamsWithContext creates a new GetOauthRefreshParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOauthRefreshParamsWithContext(ctx context.Context) *GetOauthRefreshParams {

	return &GetOauthRefreshParams{

		Context: ctx,
	}
}

// NewGetOauthRefreshParamsWithHTTPClient creates a new GetOauthRefreshParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOauthRefreshParamsWithHTTPClient(client *http.Client) *GetOauthRefreshParams {

	return &GetOauthRefreshParams{
		HTTPClient: client,
	}
}

/*GetOauthRefreshParams contains all the parameters to send to the API endpoint
for the get oauth refresh operation typically these are written to a http.Request
*/
type GetOauthRefreshParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get oauth refresh params
func (o *GetOauthRefreshParams) WithTimeout(timeout time.Duration) *GetOauthRefreshParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get oauth refresh params
func (o *GetOauthRefreshParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get oauth refresh params
func (o *GetOauthRefreshParams) WithContext(ctx context.Context) *GetOauthRefreshParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get oauth refresh params
func (o *GetOauthRefreshParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get oauth refresh params
func (o *GetOauthRefreshParams) WithHTTPClient(client *http.Client) *GetOauthRefreshParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get oauth refresh params
func (o *GetOauthRefreshParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetOauthRefreshParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
