// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetOauthProviderReader is a Reader for the GetOauthProvider structure.
type GetOauthProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOauthProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOauthProviderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOauthProviderOK creates a GetOauthProviderOK with default headers values
func NewGetOauthProviderOK() *GetOauthProviderOK {
	return &GetOauthProviderOK{}
}

/*GetOauthProviderOK handles this case with default header values.

OK
*/
type GetOauthProviderOK struct {
	Payload *models.ResponseOauthLogin
}

func (o *GetOauthProviderOK) Error() string {
	return fmt.Sprintf("[GET /oauth/:provider][%d] getOauthProviderOK  %+v", 200, o.Payload)
}

func (o *GetOauthProviderOK) GetPayload() *models.ResponseOauthLogin {
	return o.Payload
}

func (o *GetOauthProviderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseOauthLogin)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
