// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fristonio/xene/pkg/apiserver/models"
)

// GetOauthRefreshReader is a Reader for the GetOauthRefresh structure.
type GetOauthRefreshReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOauthRefreshReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOauthRefreshOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetOauthRefreshInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOauthRefreshOK creates a GetOauthRefreshOK with default headers values
func NewGetOauthRefreshOK() *GetOauthRefreshOK {
	return &GetOauthRefreshOK{}
}

/*GetOauthRefreshOK handles this case with default header values.

OK
*/
type GetOauthRefreshOK struct {
	Payload *models.ResponseJWTAuth
}

func (o *GetOauthRefreshOK) Error() string {
	return fmt.Sprintf("[GET /oauth/refresh/][%d] getOauthRefreshOK  %+v", 200, o.Payload)
}

func (o *GetOauthRefreshOK) GetPayload() *models.ResponseJWTAuth {
	return o.Payload
}

func (o *GetOauthRefreshOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseJWTAuth)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOauthRefreshInternalServerError creates a GetOauthRefreshInternalServerError with default headers values
func NewGetOauthRefreshInternalServerError() *GetOauthRefreshInternalServerError {
	return &GetOauthRefreshInternalServerError{}
}

/*GetOauthRefreshInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetOauthRefreshInternalServerError struct {
	Payload *models.ResponseHTTPError
}

func (o *GetOauthRefreshInternalServerError) Error() string {
	return fmt.Sprintf("[GET /oauth/refresh/][%d] getOauthRefreshInternalServerError  %+v", 500, o.Payload)
}

func (o *GetOauthRefreshInternalServerError) GetPayload() *models.ResponseHTTPError {
	return o.Payload
}

func (o *GetOauthRefreshInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
