// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/agent.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pipeline struct {
	// spec contains the actual spec of the pipeline. Each pipeline
	// is evaluated at the agent only. The work of the apiserver
	// is to schedule pipelines corresponding to a workflow on a number
	// of worker agents.
	Spec                 string   `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pipeline) Reset()         { *m = Pipeline{} }
func (m *Pipeline) String() string { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()    {}
func (*Pipeline) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{0}
}

func (m *Pipeline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipeline.Unmarshal(m, b)
}
func (m *Pipeline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipeline.Marshal(b, m, deterministic)
}
func (m *Pipeline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipeline.Merge(m, src)
}
func (m *Pipeline) XXX_Size() int {
	return xxx_messageInfo_Pipeline.Size(m)
}
func (m *Pipeline) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipeline.DiscardUnknown(m)
}

var xxx_messageInfo_Pipeline proto.InternalMessageInfo

func (m *Pipeline) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

type PipelineStatus struct {
	// status contains the current status of the pipeline.
	// It can be one of the preconfigured statuses for a pipeline.
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipelineStatus) Reset()         { *m = PipelineStatus{} }
func (m *PipelineStatus) String() string { return proto.CompactTextString(m) }
func (*PipelineStatus) ProtoMessage()    {}
func (*PipelineStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{1}
}

func (m *PipelineStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineStatus.Unmarshal(m, b)
}
func (m *PipelineStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineStatus.Marshal(b, m, deterministic)
}
func (m *PipelineStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineStatus.Merge(m, src)
}
func (m *PipelineStatus) XXX_Size() int {
	return xxx_messageInfo_PipelineStatus.Size(m)
}
func (m *PipelineStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineStatus proto.InternalMessageInfo

func (m *PipelineStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Pipeline)(nil), "proto.Pipeline")
	proto.RegisterType((*PipelineStatus)(nil), "proto.PipelineStatus")
}

func init() {
	proto.RegisterFile("proto/agent.proto", fileDescriptor_dd830a99d5efef4e)
}

var fileDescriptor_dd830a99d5efef4e = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0x4f, 0xcd, 0x2b, 0xd1, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x94, 0x92, 0x1c,
	0x17, 0x47, 0x40, 0x66, 0x41, 0x6a, 0x4e, 0x66, 0x5e, 0xaa, 0x90, 0x10, 0x17, 0x4b, 0x71, 0x41,
	0x6a, 0xb2, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xa4, 0xc1, 0xc5, 0x07, 0x93,
	0x0f, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x16, 0x12, 0xe3, 0x62, 0x2b, 0x06, 0xb3, 0xa0, 0xea, 0xa0,
	0x3c, 0x23, 0x1f, 0x2e, 0x1e, 0x47, 0x90, 0xf9, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42,
	0x36, 0x5c, 0x02, 0xc1, 0xc9, 0x19, 0xa9, 0x29, 0xa5, 0x39, 0xa9, 0x70, 0x1b, 0xf8, 0x21, 0x96,
	0xeb, 0xc1, 0x04, 0xa4, 0x44, 0xd1, 0x04, 0x20, 0x76, 0x28, 0x31, 0x24, 0xb1, 0x81, 0xc5, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xb0, 0x61, 0x94, 0xba, 0x00, 0x00, 0x00,
}
